# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20161020_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
