# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:31
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=b'/var/www/sae/website/static/media/images/events'), upload_to=b'', verbose_name=b'Image/Poster'),
        ),
    ]
